version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ./backend/data:/app/data
      - ./backend/logs:/app/logs
    networks:
      - elimu-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000/api/v1
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - elimu-network

networks:
  elimu-network:
    driver: bridge
