version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  elimu-hub-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - LOG_LEVEL=DEBUG
      - CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
      - REDIS_ENABLED=True
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  redis_data: 